package com.heartbeaten.network

/**
 * Transport payload containing the minimum useful heart rate metadata.
 *
 * @property bpm Heart rate value in beats-per-minute.
 * @property timestampMillis Event time (epoch millis) from the producing device.
 * @property sourceUserId Sender user/device identity.
 * @property sequence Monotonic sequence number generated by sender to aid de-duplication.
 */
data class HeartRateFrame(
    val bpm: Int,
    val timestampMillis: Long,
    val sourceUserId: String,
    val sequence: Long,
)
